### ISSUE TITLE
Require manual approval on the `plan` for deployment to prod and test

### ISSUE THREAD

**Issue by angela-tran** [cal-itp/eligibility-server#214]
[Azure docs on manual approval](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/approvals?view=azure-devops&tabs=check-pass)

I'm not sure on the benefit to this since our infrastructure changes / pipeline runs should all be triggered by opening a pull request or merging in a pull request, both of which require a developer to do.

## Acceptance criteria

- [ ] We have a good understanding of what the effects of a `test`/`prod` deployment are before they're done

## Definition of done

- [ ] The output of a `terraform plan` is reviewed before the changes are `apply`'d to `test` or `prod`

**Comment by thekaveman** [comment]
I think we're OK to close this. Since this issue opened, we separated the environments in Benefits and built a similar setup here in Eligibility Server.

As @angela-tran mentioned, a PR already requires approval. It is the responsibility of the PR author and reviewers to ensure changes in a `terraform plan` don't cause major breaking infra changes.
