### ISSUE TITLE
Refactor eligibility verification into reusable package

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/eligibility-server#38]
This is a corollary to cal-itp/benefits#141, with which this work must coordinate. See that issue for the general overview.

## Server specifics

[`eligibility_server/verify.py`](/cal-itp/eligibility-server/blob/main/eligibility_server/verify.py) is where the server-side implementation lives.

Some of the code there is setting up the `flask_restful` resource and dealing with HTTP request processing, and that would stay. Anything concerned with creating and processing the Eligibility Request and Response objects could be moved into the new package:

* [`_get_token_payload()`](/cal-itp/eligibility-server/blob/6bd419664b147801556fc3a8b0397527aebb9bdd/eligibility_server/verify.py#L63)
* [`_make_token()`](/cal-itp/eligibility-server/blob/6bd419664b147801556fc3a8b0397527aebb9bdd/eligibility_server/verify.py#L80)
* [Code that crafts the response payload](/cal-itp/eligibility-server/blob/6bd419664b147801556fc3a8b0397527aebb9bdd/eligibility_server/verify.py#L95)

**Comment by angela-tran** [comment]
I did some analysis on how easily we can replace `eligibility-server` code with calls to `eligibility-api`, given all the development that's happened in server since cal-itp/benefits#141 was done.

`_get_token_payload` and `_make_token` should be easy to do. It's almost a direct replacement - here's a diff of those two functions in `eligibility-api` vs. `eligibility-server`.
![image](https://user-images.githubusercontent.com/25497886/205170573-d67aee59-548d-4215-94b0-496b44bfc6f7.png)

`eligibility-api` does not currently have logic for [crafting the response payload](https://github.com/cal-itp/eligibility-server/blob/6bd419664b147801556fc3a8b0397527aebb9bdd/eligibility_server/verify.py#L95), so we'll need to figure out what that function should look like.
